### ISSUE TITLE
Specify oidcProvider without metadata url

### ISSUE THREAD

**Issue by ernani** [tarachandverma/ngx-openidc#1]
How can one declare an `<oidcProvider>` without it being a metadata url?
Aka, specify the params to be added statically?

**Comment by tarachandverma** [comment]
Currently it does not support individual params statically set from metadataUrl.
However, you can create oidc-config.json file, add all the params and expose via your own repository http://<your-own-repository>/oidc-config.json.
I will add support for individual params very soon.

**Comment by tarachandverma** [comment]
I've added support for individual param and test docker file.

**Comment by tarachandverma** [comment]
@ernani : I've added support to specifiy oidcProvider without metadata.

**Comment by ernani** [comment]
Thanks a lot, we are testing that feature and I will report once I am done with it. Very much appreciated!
