### ISSUE TITLE
Trying to configure nxingx-openidc with my application

### ISSUE THREAD

**Issue by smehta1215** [tarachandverma/ngx-openidc#2]
Hi! I'm trying to use your tool for authentication on my nginx application, but I'm new to this and am hoping for some help with configuration. 
I have my information as follows and a JWT certificate:

client ID = NBlLZWEzNjAtPGYxMi00
client secret = NuEkOTI4ZTUtNTlkYS00
redirect uris = https://localhost:9443
issuer = some_issuer_url
code = yes
ID token = yes
token = yes
allow introspect = yes
allow refresh grant = yes
token endpoint auth method = clientSecretPost
auth endpoint = some_ae_url
token endpoint = some_te_url
introspection endpoint = some_ie_url

My application is an nginx docker container and I followed the instructions for installation in the container, but I'm not sure what to do from this point on. What fields in the oidc-config.xml file do I need to replace with my own information? And can I just make my own json file with the token endpoint, authentication endpoint, etc and include that in the metadataUrl?
[Tara]: Now you can specify individual params

**Comment by tarachandverma** [comment]
Yes, you can make your own json file for metadata.

**Comment by tarachandverma** [comment]
For now, you can write all OIDC param into a file and exposed it as metadataUrl.

**Comment by tarachandverma** [comment]
I've added support for individual OIDC params, added docker for test as well

**Comment by tarachandverma** [comment]
@smehta1215 : I updated documentation. 
For demo, now the request flow described here - "https://github.com/tarachandverma/nginx-openidc#the-request-flow---relying-party--rp-" should work which will help you how to configure oidc-config.xml. If you need more help, let me know.

**Comment by tarachandverma** [comment]
@smehta1215 : were you able to implement your solution ?

**Comment by smehta1215** [comment]
I ended up using a client side JavaScript implementation for our solution!
Thanks for your help though.
