### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThrawnCA** [tarachandverma/ngx-openidc#4]
I'm attempting to follow the build instructions on Ubuntu 16.04, but I get a fatal error:

    cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused -Werror -g  -Wno-error -DNGX_HTTP_OPENIDC -DNGX_TCREWRITE_PCRE  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/include/apr-1 -I /usr/include/apache2 -I ../src -I ../src/service-utils -I ../src/apache-utils -I ../src/common-utils -I ../src/url-utils -I ../src/url-utils -I ../src/shm_core -I ../src/log-utils -I ../src/xml-core -I ../src/doc-parser-core -I ../src/template-core -I ../src/config-core -I ../src/oidc-core -I ../src/service-utils/service-monitor -I ../src/oidc-globals -I ../src/json-api-core -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/src/ngx_http_openidc_module.o \
        ../src/ngx_http_openidc_module.c
    ../src/ngx_http_openidc_module.c:5:23: fatal error: apr_pools.h: No such file or directory
    compilation terminated.
    objs/Makefile:1209: recipe for target 'objs/addon/src/ngx_http_openidc_module.o' failed
    make[1]: *** [objs/addon/src/ngx_http_openidc_module.o] Error 1
    make[1]: Leaving directory '/home/antuarc/osidt/nginx-openidc/nginx-1.8.0'
    Makefile:8: recipe for target 'build' failed
    make: *** [build] Error 2

Installing the `libapr1-dev` and `libaprutil1-dev` packages didn't help.

**Comment by tarachandverma** [comment]
locate apr_pools.h path on ubuntu and update following line : https://github.com/tarachandverma/nginx-openidc/blob/master/src/config#L5
Ubuntu may have apr_pools.h on different path.

**Comment by ThrawnCA** [comment]
Looks like the path should be `/usr/include/apr-1.0` instead of `/usr/include/apr-1`

Since the README says that this is tested on all *nix flavors, can this be updated to take Ubuntu into account?

**Comment by tarachandverma** [comment]
I tested mainly on CentOS and RHEL which has path /usr/include/apr-1
For ubuntu, you can change locally and try.

**Comment by ThrawnCA** [comment]
Yes, that does fix it.

Can either the code or the README be updated? I'm not certain of the best way to use different paths on different operating systems.

**Comment by tarachandverma** [comment]
yes, I will update README shortly.

**Comment by gfrankliu** [comment]
Instead of keeping two "config" files and two build scripts, why don't we change the 
`apr_dir=/usr/include/apr-1` to `apr_dir=$(apu-1-config --includedir)` so the same "config" works for both Centos/Redhat and Ubuntu?

**Comment by ThrawnCA** [comment]
Patch file for applying this:

    From e2e85a4557a69cbf288753b54c907e6fbc74eb9c Mon Sep 17 00:00:00 2001
    From: thrawnca <shell_layer-github@yahoo.com.au>
    Date: Wed, 2 May 2018 10:16:40 +1000
    Subject: [PATCH 1/2] determine APR include directory dynamically so we're more
     system-agnostic, github #4

    ---
     src/config | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

    diff --git a/src/config b/src/config
    index 1ceb80f..72edb2e 100644
    --- a/src/config
    +++ b/src/config
    @@ -2,7 +2,7 @@ ngx_addon_name=ngx_http_authz_oidc_module
     
     HTTP_MODULES="$HTTP_MODULES ngx_http_openidc_module"
     
    -apr_dir=/usr/include/apr-1
    +apr_dir=$(apu-1-config --includedir)
     apache_inc=/usr/include/apache2
     
     NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_openidc_module.c \
    -- 
    2.7.4

Patch file for cleaning up:

    From 455e9abc1a829e7141afd5977fb14376c16e63aa Mon Sep 17 00:00:00 2001
    From: thrawnca <shell_layer-github@yahoo.com.au>
    Date: Wed, 2 May 2018 10:17:07 +1000
    Subject: [PATCH 2/2] remove obsolete Ubuntu-specific config, github #4

    ---
     build_ngx_openidc_ubuntu.sh |  9 --------
     src/config.ubuntu           | 56 ---------------------------------------------
     2 files changed, 65 deletions(-)
     delete mode 100755 build_ngx_openidc_ubuntu.sh
     delete mode 100644 src/config.ubuntu

    diff --git a/build_ngx_openidc_ubuntu.sh b/build_ngx_openidc_ubuntu.sh
    deleted file mode 100755
    index 7a55247..0000000
    --- a/build_ngx_openidc_ubuntu.sh
    +++ /dev/null
    @@ -1,9 +0,0 @@
    -#! /bin/bash
    -# untar nginx
    -cp -rf src/config.ubuntu src/config
    -tar -zxvf nginx-1.8.0.tar.gz
    -cd nginx-1.8.0
    -./configure --add-module=/src --with-http_ssl_module  
    -make
    -make install
    -
    diff --git a/src/config.ubuntu b/src/config.ubuntu
    deleted file mode 100644
    index 82a6be8..0000000
    --- a/src/config.ubuntu
    +++ /dev/null
    @@ -1,56 +0,0 @@
    -ngx_addon_name=ngx_http_authz_oidc_module
    -
    -HTTP_MODULES="$HTTP_MODULES ngx_http_openidc_module"
    -
    -apr_dir=/usr/include/apr-1.0
    -apache_inc=/usr/include/apache2
    -
    -NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_openidc_module.c \
    -				$ngx_addon_dir/log-utils/logging.c \
    -				$ngx_addon_dir/xml-core/token_utils.c \
    -				$ngx_addon_dir/xml-core/xml_core.c \
    -				$ngx_addon_dir/service-utils/http-utils/http_client.c \
    -				$ngx_addon_dir/oidc-core/oidc_config.c \
    -				$ngx_addon_dir/oidc-core/oidc_config_core.c \
    -				$ngx_addon_dir/oidc-core/oidc_config_xml.c \
    -				$ngx_addon_dir/oidc-core/match_list.c \
    -				$ngx_addon_dir/oidc-core/rewrite_core.c \
    -				$ngx_addon_dir/config-core/config_core.c \
    -				$ngx_addon_dir/config-core/config_messaging_parsing.c \
    -				$ngx_addon_dir/config-core/config_messaging.c \
    -				$ngx_addon_dir/config-core/config_bindings.c \
    -				$ngx_addon_dir/config-core/config_bindings_shm.c \
    -				$ngx_addon_dir/common-utils/common_utils.c \
    -				$ngx_addon_dir/template-core/template_engine.c \
    -				$ngx_addon_dir/template-core/template_handler_url.c	\
    -				$ngx_addon_dir/doc-parser-core/doc_parser_utils.c \
    -				$ngx_addon_dir/shm_core/shm_dup.c \
    -				$ngx_addon_dir/shm_core/shm_data.c \
    -				$ngx_addon_dir/shm_core/shm_apr.c \
    -				$ngx_addon_dir/url-utils/url_utils.c \
    -				$ngx_addon_dir/json-api-core/json_parser.cpp \
    -				$ngx_addon_dir/oidc-globals/oidc_globals.c \
    -				$ngx_addon_dir/common-utils/cookie.c "				
    -				
    -CORE_INCS="$CORE_INCS $apr_dir $apache_inc $ngx_addon_dir  \
    -				$ngx_addon_dir/service-utils \
    -				$ngx_addon_dir/apache-utils \
    -				$ngx_addon_dir/common-utils \
    -				$ngx_addon_dir/url-utils \
    -				$ngx_addon_dir/url-utils \
    -				$ngx_addon_dir/shm_core \
    -				$ngx_addon_dir/log-utils \
    -				$ngx_addon_dir/xml-core \
    -				$ngx_addon_dir/doc-parser-core \
    -				$ngx_addon_dir/template-core \
    -				$ngx_addon_dir/config-core \
    -				$ngx_addon_dir/oidc-core \
    -				$ngx_addon_dir/service-utils/service-monitor \
    -				$ngx_addon_dir/oidc-globals \
    -				$ngx_addon_dir/json-api-core "				
    -CORE_LIBS="$CORE_LIBS -lm -ldl -lcurl -lz -lexpat -lapr-1 -laprutil-1 -lpcreposix -lstdc++"
    -
    -echo "config CFLAGS= $CFLAGS"
    -echo "config CORE_LIBS= $CORE_LIBS"
    -
    -CFLAGS="$CFLAGS -Wno-error -DNGX_HTTP_OPENIDC -DNGX_TCREWRITE_PCRE"
    -- 
    2.7.4
