### ISSUE TITLE
Header Configuration

### ISSUE THREAD

**Issue by jcownie** [tarachandverma/ngx-openidc#5]
Hello,

I am trying to implement this module to provide OpenID Connect authentication for my Kubernetes cluster and I am having trouble so I was hoping to get some help.  I am new to all of this, so please bear with me if I am missing something obvious.  I am currently running this server using a Docker container in a pod in my cluster.  What I am hoping to accomplish is that a user will hit a URL I have exposed for the pod, which immediately triggers a login action and sends the user to the OpenID connect provider using the URI specified under the "oidc-login" action (which includes the redirect URI).  This part works fine in my current setup.  After authentication, my ideal flow would be immediately redirect to my Kubernetes dashboard, which is an external URL.  The dashboard is provided by Kubernetes itself, and they support only a few methods of authentication.  The one I am attempting to use is passing an "Authorization: Bearer <id_token>" header when going to the URL.  Is that possible with this module?  I have tried a few different configurations but I have been unable to see any headers being passed after authenticating with my Open ID connect provider.  I tried redirecting back to the server itself and I looked at the /oidc/headers endpoint and all of the X-OIDC-* headers were populated correctly (although there was no auth header) but when going through the flow and monitoring with Chrome network developer tools, I did not see any of those headers being passed.  Am I missing something there? Is there somewhere I have to explicitly tell the module to send the correct headers? Can I configure it to send the "Authorization: Bearer" header with the ID token it gets from the OpenID Connect provider?  Any help you can provide with these questions would be greatly appreciated.  If I need to provide any more information please let me know. Thanks!

**Comment by tarachandverma** [comment]
X-OIDC-* headers are server-side headers added in HTTP incoming request before nginx proxies request to backend service.
You will not see these headers on the browser-side. as browser can only show you response headers.
Yes, you can pass id_token as "Authorization: Bearder <ID_TOKEN>"

**Comment by jcownie** [comment]
When you are referring to passing that token, are you saying that I would hardcode the <ID_TOKEN> in that example or is there some way to dynamically get the value of the token that is received from my OIDC provider in order to send it in that header?  If I am misinterpreting you then please correct me, I am just not sure how to capture the value of the token after authentication without hardcoding in the NGINX configuration.

**Comment by tarachandverma** [comment]
You would never hard-code id_token, it needs to be dynamic.
There are two flows id_token is extracted from OP and used by openidc module
1) authentication - if your application is webapp and wants to know which user is logged-in, webapp can be fronted by nginx openidc module which will automatically get id_token internally from OP and sets X-OIDC-* header every request and all subsequent request ( nginx openidc created encrypted cookie after validating id_token ) so webapp doesn't need to pass id_token as "Authorization: Bearer".
2) access resource - your application needs to get id_token from OP using OAuth2 flow and store it in cookie or local storage and every resource request pass as "Authorization: Bearder <id_token>" to resource server. Resource server needs to be fronted by nginx openidc module which will validate id_token and pass X-OIDC-* header

I believe you want to implement #1

**Comment by tarachandverma** [comment]
you can pass id_token dynamically to your urls in this format "Authorization: bearer <id_token>"
Follow API gateway flow - https://github.com/tarachandverma/nginx-openidc#the-request-flow---api-gateway
You need to configure JWT validation in oidc-config.xm
